### ISSUE TITLE
The scores run on egoschema(subset) are lower than those in the paper.

### ISSUE THREAD

**Issue by ontheway-arch** [Ziyang412/VideoTree#3] opened 2024-08-05 07:58 UTC
Hello,
Thank you for your excellent work!
I ran the code from the repository on the egoschema (subset) using the GPT-4-1106-preview model. However, the final score was more than 3 points lower than the score reported in the paper. Are there any parameter settings I might be missing?

**Comment by Ziyang412** [comment] 2024-08-06 04:52
Could you please provide more details? My reproduction using the exact same command in the repo before the pushing is below. Also I upload the intermediate results in the /results folder, hope that helps. 

<img width="1346" alt="image" src="https://github.com/user-attachments/assets/2d2f55e7-9a6f-4541-8d6e-68cb3c4d9bfe">

**Comment by ontheway-arch** [comment] 2024-08-06 06:44
Here is the script I used to run the code
python adaptive_breath_expansion.py --output_filename relevance_score.json --output_base_path /data1/user1/VideoTree/dynamic_width_expansion --model gpt-4-1106-preview --prompt_type cap_score --frame_feat_path /data-ssd1/user1/data/ego_frame_features 

python main_qa.py --output_filename standard_qa.json  --fewshot_example_path /data1/user1/VideoTree/data/egoschema/few_shot_6.json  --output_base_path output --tree_node_idx depth_expansion_res.json --model gpt-4-1106-preview --prompt_type qa_standard --temperature 0.0

![image](https://github.com/user-attachments/assets/e8f7adb9-adac-45b9-adc5-7e29ce101540)
![image](https://github.com/user-attachments/assets/b9299e4a-6924-42ef-ae4c-8be0c2b3c19c)

**Comment by Ziyang412** [comment] 2024-08-06 07:04
Could you try to use the intermediate results I uploaded in the results folder to ablate where the problem is (Just run the final QA step)? In general I feel most possible problem is the unstableness of the openai models. We are using Azure API + 1106 version.

**Comment by Ziyang412** [comment] 2024-08-08 20:51
Any updates on this? I will close the issue if the results are normal rn. Thanks


> Here is the script I used to run the code python adaptive_breath_expansion.py --output_filename relevance_score.json --output_base_path /data1/user1/VideoTree/dynamic_width_expansion --model gpt-4-1106-preview --prompt_type cap_score --frame_feat_path /data-ssd1/user1/data/ego_frame_features
> 
> python main_qa.py --output_filename standard_qa.json --fewshot_example_path /data1/user1/VideoTree/data/egoschema/few_shot_6.json --output_base_path output --tree_node_idx depth_expansion_res.json --model gpt-4-1106-preview --prompt_type qa_standard --temperature 0.0
> 
> ![image](https://private-user-images.githubusercontent.com/56793829/355340446-e8f7adb9-adac-45b9-adc5-7e29ce101540.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTA1MDksIm5iZiI6MTcyMzE1MDIwOSwicGF0aCI6Ii81Njc5MzgyOS8zNTUzNDA0NDYtZThmN2FkYjktYWRhYy00NWI5LWFkYzUtN2UyOWNlMTAxNTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIwNTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjNTZkY2IxYzA5YmExNjgyMzYyMGE3YTY3ZmExZGQ4ZGNmZDgxYWJkOTU1MTc3M2JhODRlZTE3N2FkOTEyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOYtzF0DKRr8pka9LLN-Rsasl39mfv9k3M02usc6xgo) ![image](https://private-user-images.githubusercontent.com/56793829/355340670-b9299e4a-6924-42ef-ae4c-8be0c2b3c19c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTA1MDksIm5iZiI6MTcyMzE1MDIwOSwicGF0aCI6Ii81Njc5MzgyOS8zNTUzNDA2NzAtYjkyOTllNGEtNjkyNC00MmVmLWFlNGMtOGJlMGMyYjNjMTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIwNTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NDgzZDE5MGFmNGVlMTczMTU4OTk5YmZlMmQzYmU5MWU3NTdhNzMxZGRhNzhmZDliYjM3Mzc5MGZiNjdmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E7iG7n56pnO4Ts6jIdXy-IfATkGer6HfuTjXKXs2BLc)

**Closed** 2024-08-12 05:50 UTC
